### ISSUE TITLE
findNextStep() returns distance as the crow flies

### ISSUE THREAD

**Issue by 1ec5** [mapbox/navigation.js#15]
The `distance` returned by `findNextStep()` is calculated using turf-distance – that is, as the crow flies. Typically, during turn-by-turn navigation, you want the real-time distance to the next turn to be calculated along the route line.

/cc @bsudekum @zugaldia

**Comment by bsudekum** [comment]
Good call, we should use https://github.com/Turfjs/turf-line-distance instead.
