### ISSUE TITLE
findNextStep() assumes step location is in route geometry

### ISSUE THREAD

**Issue by 1ec5** [mapbox/navigation.js#18]
@freenerd pointed out to me that the Mapbox Directions API doesn’t necessarily include the coordinate pair of each turn in the overall route geometry, so `findNextStep()` may not find any step at all. I haven’t encountered this situation in my testing, but there are some possible workarounds, like fuzzy matching.

/cc @bsudekum

**Comment by freenerd** [comment]
@1ec5 we are working on the next API version of Mapbox Directions which will include geometries per step. This will solve this potential problem.

**Comment by bsudekum** [comment]
This is done
