### ISSUE TITLE
bench if rbush is faster at calculating distance 

### ISSUE THREAD

**Issue by bsudekum** [mapbox/navigation.js#9]
https://github.com/mourner/rbush

**Comment by bsudekum** [comment]
@danpat according to @morganherlocker, rbush might not be faster here because each time the rbsuh needs to be initialized and data needs to be loaded on each api call. @morganherlocker claims turf distance is still fast enough here.

**Comment by danpat** [comment]
`rbush` would make sense if you were doing this operation on the geometry multiple times.  If you're only doing it once, then turf-distance is the way to go.

I assumed you had a route line, and then were continuously testing to see if the device was close to it.  In that case, an index like `rbush` would definitely be the way to go, you don't want to repeat those turf-distance calculations over and over again.

Sorry, seems like I misunderstood the use-case.

**Comment by bsudekum** [comment]
No worries. The api could change so that you feed it a route once and only update the user location. If things get heavy, I'd consider this change.

**Comment by danpat** [comment]
One thing to do to speed up the existing code:  do a bounding-box test before doing turf-distance.  This will save quite a few CPU cycles compared to using `turf-distance` on every segment.

Rough Javascriptish pseudocode:

```
  buffer = 0.5
  line = [[0,1],[1,2],[2,3],[3,4]]
  gps_point = [1,2]
  for(var i in line)
  {
    if (i == line.length-1) break;
    var minx = Math.min(line[i][0], line[i+1][0]);
    var maxx = Math.max(line[i][0], line[i+1][0]);
    var miny = Math.min(line[i][1], line[i+1][1]);
    var maxy = Math.max(line[i][1], line[i+1][1]);
    if ((gps_point[0] + buffer < minx) || 
        (gps_point[0] - buffer > maxx) || 
        (gps_point[1] + buffer < miny) ||
        (gps_point[1] - buffer > maxy)) 
    {
       // bounding boxes don't intersect, don't bother calculating distance
    } else {
       // bounding boxes collide, test segment with turf-distance
    }  
  }
```
